### ISSUE TITLE
Missing Verifylib

### ISSUE THREAD

**Issue by jialez0** [in-toto/in-toto-rs#15]
Hi everyone! The code of layout and verifylib is missing in this project. Do you have a development plan to complete this part of the function? I wonder when this project will have the function of verify?

**Comment by adityasaky** [comment]
Thanks for opening the issue! in-toto-rs currently doesn't implement the verification workflow, but we're always open to contributions that add this functionality. We don't have a plan at the moment to implement verification because the metadata generated here can be used with the verification workflow in https://github.com/in-toto/in-toto and https://github.com/in-toto/in-toto-golang. How do you feel about using this issue to track the addition of verifylib?

**Comment by Xynnn007** [comment]
I'd like to take this, after the merge for https://github.com/in-toto/in-toto-rs/pull/34 :)

**Comment by Xynnn007** [comment]
As [Attestation](https://github.com/in-toto/attestation) and [ITE-6](https://github.com/in-toto/ITE/blob/master/ITE/6/README.md) are still drafts and unstable, perhaps `Verifylib` should be implemented following the [spec v0.9 in 2017](https://github.com/in-toto/docs/blob/v0.9/in-toto-spec.md). Does this sound rational? @adityasaky @SantiagoTorres 

Implementing `Verifylib` could be a big work, and may involve sereval PRs. I'd like to finish this work in the following steps.
- [ ] Implement `Rulelib` :  Now `in-toto-rs` only supports serialization and deserialization for `ArtifactRule`. It should be able to apply on `materials/products`. This work will be based on [spec](https://github.com/in-toto/docs/blob/v0.9/in-toto-spec.md#433-artifact-rules), and may do some refactoring on current code.
- [ ] Implement `Verifylib`
- [ ] Documents
- [ ] Integration test using something like [demo.layout](https://github.com/in-toto/in-toto-rs/blob/master/tests/test_metadata/demo.layout)

**Comment by adityasaky** [comment]
The verification workflow that verifylib should map to is indeed from the in-toto spec (https://github.com/in-toto/docs/blob/master/in-toto-spec.md) so this seems fine to me. The proposed steps also looks reasonable to me. @SantiagoTorres what do you think?

**Comment by SantiagoTorres** [comment]
this SGTM!
